# ---------- Stage 1: Build React ----------
FROM node:20 AS build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build


# ---------- Stage 2: OpenShift-compatible Nginx ----------
FROM nginxinc/nginx-unprivileged:stable-alpine

# Copy build output
COPY --from=build /app/build /usr/share/nginx/html

# Nginx unprivileged runs on 8080
EXPOSE 8080
